ALTER TABLE "interest" DROP CONSTRAINT "interest_topic_id_fkey";
ALTER TABLE "interest" DROP CONSTRAINT "interest_user_id_fkey";
ALTER TABLE "post_like" DROP CONSTRAINT "post_like_user_id_fkey";
ALTER TABLE "post_like" DROP CONSTRAINT "post_like_post_id_fkey";
ALTER TABLE "comment_like" DROP CONSTRAINT "comment_like_user_id_fkey";
ALTER TABLE "comment_like" DROP CONSTRAINT "comment_like_comment_id_fkey";
ALTER TABLE "comment" DROP CONSTRAINT "comment_parent_comment_id_fkey";
ALTER TABLE "comment" DROP CONSTRAINT "comment_post_id_fkey";
ALTER TABLE "comment" DROP CONSTRAINT "comment_commenter_id_fkey";
ALTER TABLE "view" DROP CONSTRAINT "view_post_id_fkey";
ALTER TABLE "view" DROP CONSTRAINT "view_viewer_id_fkey";
ALTER TABLE "post_topic" DROP CONSTRAINT "post_topic_topic_id_fkey";
ALTER TABLE "post_topic" DROP CONSTRAINT "post_topic_post_id_fkey";
ALTER TABLE "post" DROP CONSTRAINT "post_subscription_plan_id_fkey";
ALTER TABLE "subscription" DROP CONSTRAINT "subscription_plan_id_fkey";
ALTER TABLE "subscription" DROP CONSTRAINT "subscription_user_id_fkey";
ALTER TABLE "subscription_plan" DROP CONSTRAINT "subscription_plan_channel_id_fkey";
ALTER TABLE "channel" DROP CONSTRAINT "channel_owner_id_fkey";
ALTER TABLE "user_credentials" DROP CONSTRAINT "user_credentials_user_id_fkey";

DROP INDEX "interest_user_id_topic_id_idx";
DROP INDEX "interest_user_id_idx";
DROP INDEX "comment_like_user_id_comment_id_idx";
DROP INDEX "comment_post_id_idx";
DROP INDEX "view_post_id_idx";
DROP INDEX "post_topic_post_id_idx";
DROP INDEX "post_topic_topic_id_idx";
DROP INDEX "subscription_plan_channel_id_idx";
DROP INDEX "subscription_user_id_plan_id_idx";
DROP INDEX "channel_owner_id_idx";

DROP TABLE "interest";
DROP TABLE "post_like";
DROP TABLE "comment_like";
DROP TABLE "comment";
DROP TABLE "view";
DROP TABLE "post_topic";
DROP TABLE "topic";
DROP TABLE "post";
DROP TABLE "subscription";
DROP TABLE "subscription_plan";
DROP TABLE "channel";
DROP TABLE "user_credentials";
DROP TABLE "user_profile";
