// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type Channel struct {
	ID          int64         `json:"id"`
	OwnerID     sql.NullInt64 `json:"owner_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Comment struct {
	ID              int64         `json:"id"`
	CommenterID     int64         `json:"commenter_id"`
	PostID          int64         `json:"post_id"`
	Content         string        `json:"content"`
	ParentCommentID sql.NullInt64 `json:"parent_comment_id"`
	CreatedAt       sql.NullTime  `json:"created_at"`
}

type CommentLike struct {
	ID        int64 `json:"id"`
	CommentID int64 `json:"comment_id"`
	UserID    int64 `json:"user_id"`
}

type Interest struct {
	UserID  int64 `json:"user_id"`
	TopicID int64 `json:"topic_id"`
}

type Post struct {
	ID                 int64  `json:"id"`
	Title              string `json:"title"`
	Description        string `json:"description"`
	ThumbnailUrl       string `json:"thumbnail_url"`
	VideoUrl           string `json:"video_url"`
	SubscriptionPlanID int64  `json:"subscription_plan_id"`
}

type PostLike struct {
	UserID    int64        `json:"user_id"`
	PostID    int64        `json:"post_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type PostTopic struct {
	PostID  int64 `json:"post_id"`
	TopicID int64 `json:"topic_id"`
}

type Subscription struct {
	UserID    int64         `json:"user_id"`
	PlanID    sql.NullInt64 `json:"plan_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type SubscriptionPlan struct {
	ID        int64        `json:"id"`
	ChannelID int64        `json:"channel_id"`
	Name      string       `json:"name"`
	Class     int32        `json:"class"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Topic struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type UserCredential struct {
	UserID    int64        `json:"user_id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	LastLogin sql.NullTime `json:"last_login"`
}

type UserProfile struct {
	ID        int64        `json:"id"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type View struct {
	ViewerID  int64        `json:"viewer_id"`
	PostID    int64        `json:"post_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}
