// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) (UserCredential, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeleteUserCredentials(ctx context.Context, userID int64) error
	DeleteUserProfile(ctx context.Context, id int64) error
	GetUserCredentials(ctx context.Context, userID int64) (UserCredential, error)
	GetUserProfile(ctx context.Context, id int64) (UserProfile, error)
	ListUserCredentials(ctx context.Context, arg ListUserCredentialsParams) ([]UserCredential, error)
	ListUserProfiles(ctx context.Context, arg ListUserProfilesParams) ([]UserProfile, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (UserCredential, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
	UpdateUsername(ctx context.Context, arg UpdateUsernameParams) (UserCredential, error)
}

var _ Querier = (*Queries)(nil)
